displayName=Splash Helper
author=PeppieLangwaus
description=A plugin that helps with splashing (Ardy Knight specifically)
tags=splashing, magic, thieving
plugins=xyz.peppie.splashhelper.SplashHelperPlugin
build=gradle
version=2.0.1